version: "3.7"
services:
  app:
    container_name: greedy-game-test-container
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/app
    command: "go run main.go"
